export const SET_ORGANIZATION = 'SET_ORGANIZATION';
export const SET_ORGANIZATIONS = 'SET_ORGANIZATIONS';
export const REMOVE_ORGANIZATION = 'REMOVE_ORGANIZATION';
export const ADD_ORGANIZATION = 'ADD_ORGANIZATION';
export const EDIT_ORGANIZATION = 'EDIT_ORGANIZATION';
