export const DATA_REQUEST_STATUS = 'DATA_REQUEST_STATUS';
export const DATA_REQUEST_FAILURE = 'DATA_REQUEST_FAILURE';

export const FORM_REQUEST_STATUS = 'FORM_REQUEST_STATUS';
export const FORM_REQUEST_FAILURE = 'FORM_REQUEST_FAILURE';
